---
title: "Book Authors"
authors:   
  - name: Thomas Debray
    orcid: 0000-0002-1790-2719
    affiliations:
      - ref: smartdas
affiliations:
  - id: smartdas
    name: Smart Data Analysis and Statistics B.V.
    city: Utrecht
format:
  html:
    toc: true
    number-sections: true
execute:
  cache: true
bibliography: 'https://api.citedrive.com/bib/0d25b38b-db8f-43c4-b934-f4e2f3bd655a/references.bib?x=eyJpZCI6ICIwZDI1YjM4Yi1kYjhmLTQzYzQtYjkzNC1mNGUyZjNiZDY1NWEiLCAidXNlciI6ICIyNTA2IiwgInNpZ25hdHVyZSI6ICI0MGFkYjZhMzYyYWE5Y2U0MjQ2NWE2ZTQzNjlhMWY3NTk5MzhhNzUxZDNjYWIxNDlmYjM4NDgwOTYzMzY5YzFlIn0=/bibliography.bib'
---

We gratefully acknowledge the contribution from the following authors:

|  Author | Affiliation |
|---|---|
| [Alf Scotland](https://orcid.org/0000-0001-9590-8617) | Biogen Digital Health International GmbH, Baar,	Switzerland |
| [Amr Makady](https://orcid.org/0000-0002-5260-1946) |  The Janssen Pharmaceutical Companies of Johnson \& Johnson, Breda,	The Netherlands |
| [Carl de Moor](https://orcid.org/0000-0002-6188-0254) |  Certara, Cambridge, MA,	United States |
| [Changyu Shen](https://orcid.org/0000-0002-4444-0943)  | Biogen, Cambridge, MA,	United States |
| [Christina Read](https://orcid.org/0009-0008-1637-6199) |	Utrecht University, Utrecht, The Netherlands |
| [Elvira D'Andrea](https://orcid.org/0000-0002-5263-3964) |	AbbVie Inc.,		Boston, MA, United States |
| [Fabio Pellegrini](https://orcid.org/0000-0001-5705-8615) |	Biogen Spain,	Madrid, Spain |
| [Gabrielle Simoneau](https://orcid.org/0000-0001-9310-6274	) |	Biogen Canada,	Toronto, Canada |
| [Gerko Vink](https://orcid.org/0000-0001-9767-1924) |  Utrecht University, Utrecht, The Netherlands |
| [Grammati Sarri](https://orcid.org/0000-0001-5536-8038) |  Cytel Inc., London, United Kingdom |
| [Hanne Oberman](https://orcid.org/0000-0003-3276-2141) |  Utrecht University, Utrecht, The Netherlands |
| [Jamie Elvidge](https://orcid.org/0000-0002-6154-8091)	| National Institute for Health and Care Excellence (NICE),		Manchester,	United Kingdom |
| [Janie Coulombe](https://orcid.org/0000-0001-5531-841X)	| Université de Montréal,	Montréal,	Canada |
| Jeremy Dietz	| National Institute for Health and Care Excellence (NICE),		London,	United Kingdom |
| [Johanna Muñoz](https://orcid.org/0000-0002-2384-5415)	| Julius Center for Health Sciences and Primary Care, University Medical Center Utrecht, Utrecht University, Utrecht, The Netherlands |
| [Konstantina Chalkou](https://orcid.org/0000-0001-9718-021X)	| Institute of Social and Preventive Medicine (ISPM), University of Bern,		Bern,	Switzerland |
| [Mohammad Ehsanul Karim](https://orcid.org/0000-0002-0346-2871)	| School of Population and Public Health, University of British Columbia,	Vancouver, Canada |
| [Tammy Jiang](https://orcid.org/0000-0002-6887-5706)	| Biogen,		Cambridge, MA,	United States |

: Authors {.hover tbl-colwidths="[35,65]"}


