on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3' # Update to most recent version of R

      - name: Install R packages into cache
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::rmarkdown
            any::kableExtra
            any::knitr
            any::dplyr
            any::ggplot2
            any::tidyverse
            any::flextable
            any::officer
            any::testthat

      - name: Install R packages with dependencies
        run: |
          Rscript -e 'install.packages("Matrix", dependencies=TRUE)'
          Rscript -e 'install.packages("survey", dependencies=TRUE)'
          Rscript -e 'install.packages("MatchIt", dependencies=TRUE)'
          Rscript -e 'install.packages("WeightIt", dependencies=TRUE)'
          Rscript -e 'install.packages("optmatch", dependencies=TRUE)'

      - name: Upgrade all R packages
        run: Rscript -e 'remotes::update_packages(ask = FALSE)'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
