on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3' # Update to most recent version of R

      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install system dependencies for textshaping
        run: sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("rmarkdown", dependencies=TRUE)'
          Rscript -e 'install.packages("kableExtra", dependencies=TRUE)'
          Rscript -e 'install.packages("knitr", dependencies=TRUE)'
          Rscript -e 'install.packages("Matrix", dependencies=TRUE)'
          Rscript -e 'install.packages("survey", dependencies=TRUE)'
          Rscript -e 'install.packages("MatchIt", dependencies=TRUE)'
          Rscript -e 'install.packages("WeightIt", dependencies=TRUE)'
          Rscript -e 'install.packages("optmatch", dependencies=TRUE)'
          Rscript -e 'install.packages("tidyverse", dependencies=TRUE)'
          Rscript -e 'install.packages("ggplot2", dependencies=TRUE)'
          Rscript -e 'install.packages("dplyr", dependencies=TRUE)'
          Rscript -e 'install.packages("flextable", dependencies=TRUE)'
          Rscript -e 'install.packages("officer", dependencies=TRUE)'
          Rscript -e 'install.packages("testthat", dependencies=TRUE)'
          Rscript -e 'install.packages("caret", dependencies=TRUE)'
          Rscript -e 'install.packages("interactionR", dependencies=TRUE)'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
