on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3' # Update to most recent version of R

      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install system dependencies for R package textshaping
        run: sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev

      - name: Install system dependencies for R package gemtc
        run: sudo apt-get install -y libglpk-dev

      - name: Install system dependencies for JAGS
        run: sudo apt-get install -y r-cran-rjags

      - name: Install system dependencies for R package pdftools
        run: sudo apt-get install -y libpoppler-cpp-dev

      - name: Install TinyTeX
        run: |
          Rscript -e 'install.packages("tinytex")'
          Rscript -e 'tinytex::install_tinytex()'
          Rscript -e 'tinytex:::install_prebuilt()'

      - name: Install R packages from CRAN
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::rmarkdown
            any::caret
            any::devtools
            any::dplyr
            any::gemtc
            any::ggmice
            any::ggplot2
            any::ggpubr
            any::gridExtra
            any::jomo
            any::kableExtra
            any::knitr
            any::MatchThem
            any::metafor
            any::mice
            any::missForest
            any::mitml
            any::mixgb
            any::naniar
            any::netmeta
            any::remotes
            any::roxygen2
            any::sandwich
            any::tidyverse
            any::table1


      - name: Install R packages from GitHub
        run: Rscript -e 'devtools::install_github("MathiasHarrer/dmetar",  auth_token = Sys.getenv("GITHUB_PAT"))'

      - name: Install remaining R packages
        run: |
          Rscript -e 'install.packages("Matrix", dependencies=TRUE)'
          Rscript -e 'install.packages("survey", dependencies=TRUE)'
          Rscript -e 'install.packages("MatchIt", dependencies=TRUE)'
          Rscript -e 'install.packages("WeightIt", dependencies=TRUE)'
          Rscript -e 'install.packages("optmatch", dependencies=TRUE)'
          Rscript -e 'install.packages("flextable", dependencies=TRUE)'
          Rscript -e 'install.packages("officer", dependencies=TRUE)'
          Rscript -e 'install.packages("testthat", dependencies=TRUE)'
          Rscript -e 'install.packages("interactionR", dependencies=TRUE)'
          Rscript -e 'install.packages("jarbes", dependencies=TRUE)'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
